let data = [

    {
        name: "Eye Cream",
        img: "/images/1.jpg",
        slug: "Eye Cream",
        price: "45",
        description: "simply dummy text of the printing and typesetting.",
        instock: '0',
        rating:"5",
        numberofrating:"10",
    },
    {
        name: "Bio-shroom",
        img: "/images/2.jpg",
        slug: "Bio-shroom",
        price: "77",
        description: "simply dummy text of the printing and typesetting.",
        instock: '13',
        rating:"1",
        numberofrating:"155",
    },
    {
        name: "Coffee Bean",
        img: "/images/3.jpg",
        slug: "Coffee Bean",
        price: "35",
        description: "simply dummy text of the printing and typesetting.",
        instock: '133',
        rating:"5",
        numberofrating:"19",
    },
    {
        name: "Eye Cream",
        img: "/images/4.jpg",
        slug: "Eye Cream",
        price: "44",
        description: "simply dummy text of the printing and typesetting.",
        instock: '133',
        rating:"4",
        numberofrating:"50",
    },
    {
        name: "Eye Cream",
        img: "/images/5.jpg",
        slug: "Eye Cream",
        price: "13",
        description: "simply dummy text of the printing and typesetting.",
        instock: '33',
        rating:"5",
        numberofrating:"43",
    },
    {
        name: "Eye Cream",
        img: "/images/6.jpg",
        slug: "Eye Cream",
        price: "64",
        description: "simply dummy text of the printing and typesetting.",
        instock: '133',
        rating:"2.5",
        numberofrating:"150",
    },
    {
        name: "Eye Cream",
        img: "/images/7.jpg",
        slug: "Eye Cream",
        price: "99",
        description: "simply dummy text of the printing and typesetting.",
        instock: '63',
        rating:"3.5",
        numberofrating:"168",
    },
    {
        name: "Eye Cream",
        img: "/images/8.jpg",
        slug: "Eye Cream",
        price: "66",
        description: "simply dummy text of the printing and typesetting.",
        instock: '63',
        rating:"4",
        numberofrating:"145",
    }

]

export default data;